Решение задач 1.2.13 и 1.2.19. (Пока без тестов)
v-log/Training pull request #10
Opened 2016-09-07 15:29 UTC by v-log

Ввод: 6 аргументов через пробел - на каждую транзакцию по три.
Исключения будут детализированы.

2016-09-11 23:44 UTC, v-log commented
@be9 Вопрос: если пользоваться исключением только для вывода сообщения об ошибке, по большому счету, нет разницы какое использовать? (кроме схожести названия исключения и причины ошибки)

2016-09-15 13:31 UTC, be9 commented on src/Ex_1_2_13_1_2_19/Transaction.java
> +        else throw new ArithmeticException("Введите три аргумента через пробел:" +
Ну не ArithmeticException здесь. Хотя бы IllegalArgumentException.

2016-09-15 13:35 UTC, be9 commented on src/Ex_1_2_13_1_2_19/Transaction.java
> +            if (!customerTemp.matches("[A-Z]([a-z])+") &&
С русскими буквами работать не будет. Посмотри здесь: http://stackoverflow.com/questions/4304928/unicode-equivalents-for-w-and-b-in-java-regular-expressions

2016-09-15 13:36 UTC, be9 commented on src/Ex_1_2_13_1_2_19/Transaction.java
> +}
Не хватает здесь `compareTo()` и `hashCode()`.

2016-09-15 13:37 UTC, be9 commented on src/Ex_1_2_13_1_2_19/Date.java
> +        month = Integer.parseInt(fields[0]);
Наивная реализация, где-то же у тебя была получше.

2016-09-15 13:38 UTC, be9 requested changes

2016-09-18 01:08 UTC, v-log commented
Думал насчет Date это не принципиально для задачи. Заменил на SmartDate. Пришлось его дополнить тоже hashCode(). Понял, что лучше проработанны

2016-09-19 06:26 UTC, be9 commented on src/Ex_1_2_12/SmartDate.java
> +        int hash = 1;
Здесь можно проще. Для даты 19.09.2016 просто верни число 20160919. Они все в int влезут.

2016-09-19 06:29 UTC, be9 commented on src/Ex_1_2_12/SmartDate.java
> +        if(this.month() != that.month()) return false;
Такие вещи лучше записывать прямо в выражениях:

```java
return this.month() == that.month() && this.day() == that.day() && this.year() == that.year(); 
```

2016-09-19 06:30 UTC, be9 requested changes
А почему остались и Date, и SmartDate? Одного класса не хватит?

2016-09-21 14:51 UTC, be9 commented on tests/Ex_1_2_13_1_2_19/TransactionTest.java
> +            fail("Should throw ArithmeticException");
"Should throw IllegalArgumentException", видимо

2016-09-21 14:53 UTC, be9 approved these changes
Маленькая придирка осталась.

2016-09-22 13:04 UTC, v-log commented on tests/Ex_1_2_13_1_2_19/TransactionTest.java
> +            fail("Should throw ArithmeticException");
Упустил

2016-09-22 13:05 UTC, v-log commented on tests/Ex_1_2_13_1_2_19/TransactionTest.java
> +            fail("Should throw ArithmeticException");
@be9 Упустил

2016-09-23 08:17 UTC, merged