1 3 4
v-log/Training pull request #11
Opened 2016-09-14 23:08 UTC by v-log

2016-09-15 13:43 UTC, be9 commented on src/Ex_1_3_4/Parentheses.java
> +            if (Arrays.asList(parOpen).contains(ch))
Это не очень эффективно. На каждом шаге для каждого символа (!) оба массива превращаются в список. Можно было бы сделать проще:

```java
private static final PAR_OPEN = "[({";
private static final PAR_CLOSE = "])}";

public static boolean parenthesesBalanced(String input) {
    // ...
    for (char ch: inputChars) {
        if (PAR_OPEN.indexOf(ch) >= 0) {
            // Открывающая скобка
            // ...
        } else if (PAR_CLOSE.indexOf(ch) >= 0) {
            // Закрывающая скобка
            // ...
        }
    }
}


    }
```

2016-09-15 13:47 UTC, be9 commented on src/Ex_1_3_4/ResizingArrayStack.java
> +        Item item = a[--N];
На пустом стеке здесь упадёт. В этом случае лучше сгенерировать исключение.

2016-09-15 13:47 UTC, be9 requested changes

2016-09-16 12:52 UTC, v26 commented on src/Ex_1_3_4/Parentheses.java
> +            if (Arrays.asList(parOpen).contains(ch))
Решение прямо-таки претендует на гениальное

2016-09-16 12:56 UTC, v-log commented on src/Ex_1_3_4/ResizingArrayStack.java
> +        Item item = a[--N];
Я два раза затупил:
1) Добавил ResisingArrayStack, а в Parentheses использовал обычный Stack (так, конечно, не нужен Resising, просто обидно);
2) В библиотеке algs4.jar ResisingArrayStack итак есть (с исключение в том месте, где Вы указали).

2016-09-16 13:49 UTC, be9 commented on tests/Ex_1_3_4/ParenthesesTest.java
> +    }
Тут не хватает традиционной пустой строки, на которой тоже не должно упасть. 

Хорошо бы также добавить тест с угловыми скобками. Поскольку мы их за скобки не считаем, то, например, строка `><` будет корректной.

Один из принципов тестирования: проверять не только «строгость» (отбраковывание некорректных значений), но и «мягкость» (т.е. допущение значений корректных, но близких к некорректным). Вообще, в задачах классификации (а функция-предикат, возвращающая `bool`, — бинарный классификатор) есть два вида ошибок: «false positive» (когда классификатор возвращает `true`, а надо бы `false`) и «false negative» (когда `false`, а надо бы `true`). При написании тестов нужно проверять и на то, и другое.

Простой пример: тестируем функцию `f(x) = x > 0`. Нужно проверить, что для 0 она возвращает `false`, а для 1 – `true`. Если мы в реализации ошиблись и написали `return x >= 0`, то тест это поймает, потому что он проверяет границу между классами. Эту логику можно экстраполировать и на нечисленные значения, как в этой задаче.

2016-09-16 14:00 UTC, be9 requested changes
Ещё немного 😉

2016-09-18 02:30 UTC, v-log commented
Вот уж искусство

2016-09-21 14:55 UTC, be9 approved these changes

2016-09-21 14:55 UTC, merged