1 3 10
v-log/Training pull request #19
Opened 2016-09-23 22:50 UTC by v-log

2016-09-23 22:51 UTC, v-log commented
Забыл amend сделать на первый коммит. Там все некрасиво...

2016-09-24 05:03 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +            int precedence = opsStr.indexOf(opSymbol) / 2;
Не очень удачное решение с т.з. дальнейшего расширения. Лучше уж сделать отдельный массив, в котором положить приоритеты в том же порядке. Искать индекс в строке, а доставать precedence из массива.

2016-09-24 05:04 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +    private static StringBuilder output = new StringBuilder();
StringBuilder лучше порождать прямо внутри функции. Не очень понятно, зачем ему болтаться всё время.

2016-09-24 05:07 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +                if ( !ops.isEmpty() && opsStr.indexOf(ops.peek().opSymb()) == 0 ) operandAfterPar = true;
Что-то ну очень сложное выражение. Почему бы не `ops.peek().opSymb() == '('` после `&&`?

2016-09-24 05:09 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +            if ( opsStr.indexOf(ch.opSymb()) == 0) {
Та же фигня (см. выше).

2016-09-24 05:09 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +            if ( opsStr.indexOf(ch.opSymb()) == 1 ) {
А здесь `== ')'`.

2016-09-24 05:09 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +                while (!ops.isEmpty() && opsStr.indexOf(ops.peek().opSymb()) != 0) {
`!= '('`

2016-09-24 05:10 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +            if ( opsStr.indexOf(ch.opSymb()) > 1 ) {
`!= '(' && != ')'`

2016-09-24 05:11 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +                if (parOpenCount > 0 && !ops.isEmpty() && opsStr.indexOf(ops.peek().opSymb()) == 0
И снова. Кстати, ещё идея: можно добавить методы-проверялки в класс `Operator`. Тогда здесь третья часть выражения была бы `ops.peek().isLeftParen()`.

2016-09-24 05:15 UTC, be9 requested changes
Основное, что затрудняет понимание кода — магические сравнения indexOf c 0, 1 и т.д. См. комменты.

2016-09-24 05:15 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +            String inStr1 = "A * B + C * D";
Именно для таких вещей и придумали массивы 😜

2016-09-24 06:42 UTC, v-log commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +            int precedence = opsStr.indexOf(opSymbol) / 2;
Блин, сначала так было...) Ну почти так. В общем, понял, переделаю

2016-09-24 06:48 UTC, v-log commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +    private static StringBuilder output = new StringBuilder();
Ааа, это выносил когда делал отдельно метод opOut, чтобы он тоже видел output. Потом метод изменить немного додумался, а это не перенес

2016-09-24 06:49 UTC, v-log commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +                if ( !ops.isEmpty() && opsStr.indexOf(ops.peek().opSymb()) == 0 ) operandAfterPar = true;
Соответственно, когда были static final переменные для операторов, сравнение шло с ними. Это потом когда решил сократить, так сделал. Изменю

2016-09-24 08:52 UTC, be9 commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +    private static StringBuilder output = new StringBuilder();
Общий принцип: чем меньше время жизни у переменной, тем лучше. Долгоживущие переменные создаются либо по нужде, либо в целях оптимизации производительности.

2016-10-09 18:20 UTC, v-log commented on src/Ex_1_3_10/INFIXtoPostfix.java
> +                if (parOpenCount > 0 && !ops.isEmpty() && opsStr.indexOf(ops.peek().opSymb()) == 0
Исправил определение оператора - теперь сравнивается явно с символом оператора. Посмотрите,теперь лучше смотрится, и, может, isLeftParen() (и другие, соответственно) необязательно реализовывать в данном случае? (получается, все равно для каждого символа отдельную проверку нужно будет делать, а здесь они не так часто повторяются)

2016-10-09 18:21 UTC, v-log commented
P.S. Закоммитил я, просто email был не тот настроен.

2016-10-12 19:32 UTC, v-log commented
@be9 P.S. Закоммитил я, просто email был не тот настроен.

2016-10-15 02:52 UTC, merged