Решение задач 1.3.24-1.3.26
v-log/Training pull request #20
Opened 2016-10-23 22:30 UTC by v-log

2016-10-23 22:36 UTC, v-log commented
@be9 Не могу понять как реализовать "удаление ни одного элемента" для remove(). Null же этот аргумент не может быть, а на любые другие варианты выдаст IllegalArgumentException из-за отсутствия такого элемента в списке.
Вопрос по equals() : там есть unchecked cast, но перед этим мы проверяем, чтобы сравниваемые элементы были одного класса; здесь необязательно реализовывать проверку при cast?

2016-10-25 09:15 UTC, be9 commented
@v-log это тогда на `IllegalArgumentException`.

2016-10-25 09:16 UTC, be9 commented
Про "проверку при cast" вопрос не понял :)

2016-10-25 11:28 UTC, v-log commented
@be9 Ну вот когда мы из Object делаем cast до LinkedListStack возникает `unchecked cast`, что, как мне казалось, нежелательно. Здесь можно пренебречь проверкой при таком cast?

2016-10-25 18:16 UTC, be9 commented
Пренебреги. Вообще, это уже джавовщина голимая, надо делать как принято, я тут точно не знаю :)18:28, 25 октября 2016 г., "v-log" <notifications@github.com>:@be9 Ну вот когда мы из Object делаем cast до LinkedListStack возникает unchecked cast, что, как мне казалось, нежелательно. Здесь можно пренебречь проверкой при таком cast?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

2016-10-26 09:48 UTC, v-log commented
@be9 Понял. Ну тогда здесь всё (в смысле, готов к проверке).

2016-10-31 10:13 UTC, be9 requested changes

2016-10-31 10:13 UTC, be9 commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +        int indexToRemoveAfterTemp = -1;
Вся эта возня с индексами не нужна. Здесь хватит одного цикла без итераторов.

2016-10-31 10:13 UTC, be9 commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +        for(Iterator<Item> iterator = this.iterator(); iterator.hasNext(); ) {
Опять та же фигня + полное дублирование логики поиска node по item. В таких случаях обычно пишется функция с`findNode(Item)`.

2016-10-31 16:06 UTC, v-log commented
@be9 Переместил в отдельный метод (в 1.3.31 только додумался до этого, потом уже и Вы здесь написали), итератор убрал, но насчет индексов я не совсем понимаю в чем "возьня" заключается.
В отдельном методе органичнее выглядит теперь?

2016-11-01 11:19 UTC, be9 commented
@v-log С индексами есть несколько проблем.

*Проблема быстродействия*. Твой код делает два прохода по списку, хотя достаточно одного. 

```java
public void insertAfter(Item itemToInsertAfter, Item itemToInsert) throws IllegalArgumentException {
    Node node = this.first;

    while (node != null) {
        if (node.item.equals(itemToInsertAfter))
            break;

        node = node.next;
    }

    if (node == null)
        throw new IllegalArgumentException(...);
   
    Node nodeToInsert = new Node();
    nodeToInsert.item = itemToInsert;
    insertAfterInner(node, nodeToInsert);
}
```

Можно сделать и через итераторы то же самое, но тогда надо расширить интерфейс итератора, позволив забирать оттуда указатель на `Node`.

*Проблема идеологическая*. Работа с индексами уместна только в контексте структур с произвольным доступом (разные виды массивов). Для работы со списками используются указатели. Также можно использовать итераторы, ведь итератор — это обобщение указателя, индекса и т.д. Но внутри итератор списка всё равно содержит указатель.

Попытка «говорить» со структурой данных не на её «родном языке» (сиречь, интерфейсе) чаще всего порождает проблемы и указывает либо на возможность иной реализации, либо на неправильный выбор структуры данных. По второму случаю: есть, скажем так, «язык задачи» (используемые запросы) и «язык структуры данных» (интерфейс). Структура подбирается так, чтобы эти языки по возможности совпадали.

2016-11-01 12:10 UTC, v-log commented
@be9 Осознал.

2016-11-04 06:32 UTC, be9 requested changes
Уже лучше, остались небольшие замечания.

2016-11-04 06:32 UTC, be9 commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +        while (nodeToInsertAfter != null) {
Этот код дублируется, и я бы его вынес всё же в отдельный метод, типа `findNodeByItem`.

2016-11-04 06:32 UTC, be9 commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +
Посюда бы вынес.

2016-11-04 06:32 UTC, be9 commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +        int noMatchCount = 0;
Счётчик здесь избыточен. Хватит булевого флага: `boolean deleted = false;`

2016-11-04 06:32 UTC, be9 commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +                N--;
И сюда вставить `deleted = true;`

2016-11-04 06:32 UTC, be9 commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +                noMatchCount++;
Это тогда вообще не нужно.

2016-11-04 06:32 UTC, be9 commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +        if(noMatchCount == listSize) {
А здесь `if (!deleted) { ... }`

2016-11-04 09:50 UTC, v-log commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +        while (nodeToInsertAfter != null) {
@be9 Глупая ошибка, не доглядел

2016-11-05 09:54 UTC, be9 reviewed
Последняя мелочь.

2016-11-05 09:54 UTC, be9 commented on src/Ex_1_3_24__1_3_26/LinkedListStack.java
> +        int noMatchCount = 0;
Тогда и переменная здесь не нужна.

2016-11-08 16:58 UTC, v-log commented
Fixes #13

2016-11-14 06:37 UTC, merged