Решение задачи 1.3.31
v-log/Training pull request #21
Opened 2016-10-31 14:33 UTC by v-log

2016-11-01 13:46 UTC, be9 requested changes

2016-11-01 13:46 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +        N--;
Здесь забыл поправить обратную связь (`first.next.previous`).

2016-11-01 13:46 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +        for (int i = 0; i < this.size(); i++) {
Лучше сделать цикл `while (tempNode != null) { ... }`, будет более «списочно» смотреться.

2016-11-01 13:46 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +        penult = getDoubleNodeAt(this.size() - 2);
Смотрю я на эти мучения и думаю, что проще в класс добавить ещё одно поле: `DoubleNode last = null`. Это полностью решит все проблемы с поиском конца, требующим N операций.

Есть ещё один интересный альтернативный вариант: сделать список кольцевым, но лучше пока с `last`.

2016-11-01 13:46 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +        int indexToRemoveAfter = indexSearch(itemToRemoveAfter);
Так, ну про индексы мы уже поговорили.

2016-11-04 07:11 UTC, be9 requested changes
Дополнительные соображения. 
1. Давай упростим жизнь и в методы типа `insertAfter` будем передавать `Node` (или итератор). Линейные поиски по `Item` всё же не в духе списков. Кроме того, в условии 1.3.24 указывается вот что: "Write a method removeAfter() that takes a linked-list Node as argument". Т.е. даже в задачах с односвязными списками (#20) предполагался интерфейс без `Item`. Но там уж ладно.
2. Поскольку в реализацию с `last` закрались ошибки, полезно понять, как тестировать такие вещи. Предлагаю две идеи.

**Идея 1**. Какие различные фактуры списков существуют? Тут ясно, что это пустой список, список с одним элементом и список с 2 и более элементов. 

Где над списком можно совершать операции? Понятно, что в начале, в серединке и в конце.

Добавляя сюда список операций (различные виды вставки и удаления), мы получаем все варианты, которые в идеале нужно протестировать. Но даже если не тестировать, их нужно иметь в голове.

**Идея 2**. Для тестов очень хорошо подходит проверка инвариантов. Какие у списка инварианты? Их несложно выделить:
- Если `first == last`, то они либо оба равны `null`, и тогда это пустой список (`N == 0`), либо не равны `null`, и тогда `N == 1`.
- Если `first != last`, то, прошагав от `first` до `last` по прямым ссылкам, мы должны насчитать `N` узлов. Обратный проход от `last` до `first` тоже должен дать `N` узлов.
- Для непустого списка выполняются условия `first.previous == null` и `last.next == null`.
- Для каждого узла `node`: если `node != first`, то должно выполняться условие `node.previous.next == node`. Если `node != last`, то условие `node.next.previous == node`.

Если все эти инварианты соблюдены, то список целостен. Тогда тесты любой операции сводятся к локальной проверке (если вставка, то что элемент вставился куда надо) и к проверке инвариантов (вынесенной в отдельную функцию, ессно).

Данный подход, может быть, немного избыточен для этой задачи, но он _системен_. Мышь (баг) не проскочит :)

2016-11-04 07:11 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +            last = first;
Уверен? Если `first.next == null`, то `first` после строки 66 будет равен `null`, а `last`, получается, будет равен старому значению `first`.

2016-11-04 07:11 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +        }
А если `last == null`? Это случай пустого списка, где вставка что в конец, что в начало — одно и то же. Но `push` у тебя может вставить в пустой список, а `insertAtEnd`, получается, нет.

2016-11-04 07:11 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +        if(this.isEmpty()) {
Я бы не писал `this.`

А то в одних местах пишешь, в других — нет.

2016-11-04 07:11 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +    public void removeAfter(Item itemToRemoveAfter) throws IllegalArgumentException {
Обращаю внимание, что в условии задания говорится «... and remove a given node».

В этом ключевое различие между интерфейсами односвязного и двусвязного списков: если у первого вставка и удаление совершаются _после_ того узла, который мы передаём, то у последнего мы можем удалить сам передаваемый элемент, а вставить хоть до, хоть после.

2016-11-04 07:11 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +            }
А если он последний, то надо бы обновить `last`.

2016-11-04 07:11 UTC, be9 commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +        int noMatchCount = 0;
Со счётчиком см. комментарий [здесь](https://github.com/v-log/Training/pull/20#discussion_r86494436).

2016-11-04 12:53 UTC, v-log commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +        if(this.isEmpty()) {
@be9 Сначала везде было this, потом узнал, что можно без него, и убрал. Недоубирал.

2016-11-04 12:55 UTC, v-log commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +    public void removeAfter(Item itemToRemoveAfter) throws IllegalArgumentException {
Так ведь за удаление именно требуемого элемента отвечает метод remove().

2016-11-04 12:55 UTC, v-log commented on src/Ex_1_3_31/DoubleLinkedListStack.java
> +    public void removeAfter(Item itemToRemoveAfter) throws IllegalArgumentException {
@be9 Так ведь за удаление именно требуемого элемента отвечает метод remove().

2016-11-04 13:05 UTC, v-log commented
@be9 Изначально проблема с передачей Node в методы была в том, что Node никак не получить было, и я не понимал, как пользователь сможет работать с Node, поэтому я предложил через Item заходить. Итератор тоже Item возвращает.

Тогда сделать в итераторе возврат Node?

Я понял Ваш посыл насчет поиска по списку через Item, и понимаю, что сделал костыли, просто не представлял как это будет выглядеть для конечного пользователя.

Я сторонник системного подхода, но здесь, должен признать, ринулся "в лоб". Замечания понял.

2016-11-05 09:51 UTC, be9 commented
Пусть итератор возвращает Node, а в методы вместо `Item` и `Node` передаётся итератор.

2016-11-18 23:34 UTC, v-log commented
@be9 В тестовых методах перед каждым отдельным тестом сделал отступ в две строки для лучшей читаемости - это приемлемо? Или лучше сделать комментарии типа 
`// ***** Тест на перехват исключения при удалении `  ?

2016-11-21 04:07 UTC, be9 commented
@v-log Нормально так.

2017-01-10 15:16 UTC, v-log commented
@be9 Здесь Вам только осталось проверить последние изменения

2017-01-11 15:03 UTC, merged