Половина задания - реализация через префиксное дерево.
v-log/Training pull request #23
Opened 2017-01-09 16:43 UTC by v-log

Вторая половина  - то же самое через хеширование.

2017-01-11 11:33 UTC, v-log commented
Fixes #24

2017-01-11 11:35 UTC, v-log commented
@be9 Пушнул с windows, там логин старый остался...

2017-01-11 15:14 UTC, be9 reviewed
В принципе нормально, хотя тесты конечно бы не помешали. Но, похоже, у тебя и без тестов есть, чем заняться :)

2017-01-11 15:14 UTC, be9 commented on src/Laba_1_Trie/TrieTree.java
> +    private static LinkedList<Character> listForPrint;
Это не должно быть членом класса.

2017-01-11 15:14 UTC, be9 commented on src/Laba_1_Trie/TrieTree.java
> +определения уникальных строк в массиве строк;
Под «определением уникальных строк» обычно имеется в виду получение всего множества уникальных строк, а не проверка каждой строки, уникальна она или нет. 

Эта задача как раз решается путём вставки всех строк в контейнер по ключу и последующим обходом контейнера.

Т.е. вся эта кухня с `isUnique` не нужна.

2017-01-11 15:14 UTC, be9 commented on src/Laba_1_Trie/TrieTree.java
> +        listForPrint = new LinkedList<>();
Собственно, эту переменную можно здесь и создать, раз она всё равно передаётся в `printTrieInner`.

2017-02-26 14:43 UTC, v-log commented
Исправляю. В префиксном дереве без итератора можно обойтись?)

2017-02-26 14:45 UTC, v-log commented
@be9 Исправляю. В префиксном дереве без итератора можно обойтись?)

2017-03-02 16:44 UTC, v-log commented
@be9 В тестах инвариант для пустого дерева содержит такую же проверку, что и сам isEmpty() - решил, что лучше сделать хоть так, чем не делать совсем (на случай если в классе поменяется логика определения isEmpty()). Так как нет size(), iterator(), в insertTest() проверяется только целостность дерева.

2017-03-03 02:54 UTC, be9 requested changes
В целом хорошо, но предлагаю ещё несколько доработок:

1. Выкинуть свою реализацию стека, взять `java.util.Stack`.
2. Код `if (!stringToRemove.matches("[\\p{Lu}\\p{Ll}]+")) { ... }` повторяется аж 3 раза, его хорошо бы вынести в статический метод класса (эвристика для таких случаев: 2 раза повторение еще терпимо, но 3 — уже точно надо выносить).
3. Добавить `size()`, здесь это нужно делать путем инкремента и декремента счётчика в `Trie`.

На итератор можно забить, он делается через стек итераторов по Map. Но реализуй, если интересно.

2017-03-03 02:54 UTC, be9 commented on src/Laba_1_Trie/StackArray.java
> +public class StackArray<Item> implements Iterable<Item> {
Вообще, стек можно было взять джавовский: https://docs.oracle.com/javase/7/docs/api/java/util/Stack.html

Используешь же ты системный Map...

2017-03-10 21:25 UTC, v-log commented
@be9 Промучался с итератором, не получилось... Не хотел сдаваться, но чтобы опять не залипать пока оставлю эту затею. Потом как-нибудь сделаю.

2017-03-12 23:08 UTC, v-log commented
@be9 Итератор сделал (с помощью костылей, правда) - выявилось некорректное удаление в remove(). Делаю.

2018-04-10 07:45 UTC, closed without merging