Решение задачи 1.4.16
v-log/Training pull request #33
Opened 2017-03-19 20:11 UTC by v-log

Fixes #30

2017-03-19 20:40 UTC, v-log commented
@be9 
NlogN + N ~ NlogN

2017-03-20 02:23 UTC, be9 requested changes
Идея уловлена верно, часто алгоритмы строятся по принципу "отсортируем за NlogN, а потом что-нибудь сделаем за N", общее время все равно NlogN.

Но — пара мелочей.

2017-03-20 02:23 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_16/ClosestPairFinder.java
> +        for (int i = 0; i < a.length - 1; i++) {
Тут упадёт, если передать пустой массив. Нужно добавить проверку и кидать исключение.

2017-03-20 02:23 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_16/ClosestPairFinder.java
> +            double temp = Math.abs(a[i + 1] - a[i]);
А зачем тут `.abs`, если массив отсортирован? `a[i + 1] - a[i]` всяко будет больше или равно 0.

2017-03-21 19:11 UTC, v-log commented on src/Algorithms_Chapter_1/Ex_1_4_16/ClosestPairFinder.java
> +            double temp = Math.abs(a[i + 1] - a[i]);
Не подумал...

2017-03-22 02:58 UTC, be9 approved these changes
Хорошо, только 0 смотрится странно.

2017-03-22 02:58 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_16/ClosestPairFinder.java
> +        double[] a = new double[0];
Ну уж прям 0 :)

2017-04-02 19:30 UTC, v-log commented
@be9 Ставил, когда тестировал

2017-04-03 02:07 UTC, be9 approved these changes
👍

2017-04-04 18:02 UTC, merged