Решение задачи 1.4.20
v-log/Training pull request #40
Opened 2017-04-02 19:28 UTC by v-log

2017-04-02 19:31 UTC, v-log commented
#40 
@be9 Без проверки - битонический массив или нет

2017-04-03 02:32 UTC, be9 requested changes
В целом нормально (за минусом мест, которые можно выразить проще). В ~3lg(N) сравнений вписался.

Необязательный вариант улучшения: объединить rankDirect и rankIndirect в одну процедуру. По сути, они отличаются лишь диапазоном поиска (можно его передавать непосредственно как два аргумента) и направлением сравнения. Последнее можно передавать либо как булевский флаг, либо как предикат (в Java 8 появились лямбды).

2017-04-03 02:32 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +
Здесь проверку бы на длину с киданием Exception. Какая может быть минимальная длина у битонического массива?

2017-04-03 02:32 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +            max = lo + (hi - lo) / 2;
`max = (lo + hi) / 2;` выглядит проще, а делает то же самое.

2017-04-03 02:32 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +            if (hi != max && bitonicArray[max + 1] - bitonicArray[max] > 0) {
`bitonicArray[max + 1] > bitonicArray[max]`

2017-04-03 02:32 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +            } else if (lo != max && bitonicArray[max] - bitonicArray[max - 1] < 0) {
`bitonicArray[max] < bitonicArray[max - 1]`

2017-04-03 02:32 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +    private static boolean rankDirect(int[] bitonicArray, int max, int key) {
А что в названиях функций значит direct и indirect?

2017-04-03 02:32 UTC, be9 commented on tests/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearchTest.java
> +
Добавь сюда ещё минимальный битонический массив.

2017-04-03 02:58 UTC, v-log commented
@be9 Про лямбды тоже думал, но пока не разобрался с этим.

2017-04-03 02:58 UTC, v-log commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +
3 элемента, думаю

2017-04-03 02:59 UTC, be9 commented
@v-log я тут собрал небольшой примерчик: https://repl.it/GrS0/0

2017-04-03 03:00 UTC, v-log commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +    private static boolean rankDirect(int[] bitonicArray, int max, int key) {
@be9 direct - когда возрастание идет (перед максимумом), Indirect - убывание (после макс.)

2017-04-03 03:01 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +
👍

2017-04-03 03:02 UTC, be9 commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +    private static boolean rankDirect(int[] bitonicArray, int max, int key) {
Ну я по реализации догадался, конечно. Просто direct/indirect – это "прямой"/"непрямой". Наверное, лучше назвать было бы ascending/descending.

2017-04-03 03:06 UTC, v-log commented on src/Algorithms_Chapter_1/Ex_1_4_20/BitonicSearch.java
> +    private static boolean rankDirect(int[] bitonicArray, int max, int key) {
@be9 Этого больше не повторится...)

2017-04-07 18:37 UTC, v-log commented
Упрощен код для указанных в замечаниях операций

2017-04-08 01:24 UTC, be9 approved these changes

2017-04-08 10:04 UTC, merged