Алгоритм сортировки выбором на Ruby - ч.1 и ч.2
v-log/Training pull request #41
Opened 2017-04-25 16:47 UTC by v-log

2017-04-25 16:52 UTC, v-log commented
@be9 sorted?() работает только для части 1

2017-04-26 03:09 UTC, be9 requested changes
Поздравляю с первой программой на Ruby!

И мы сразу будем учиться, как писать на Ruby, чтобы было «как доктор прописал».

2017-04-26 03:09 UTC, be9 commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +
Это можно написать в одну строчку:

```ruby
(0...a.size - 1).all? { |i| a[i] <= a[i+1] }
```
Обрати внимание, как работают блоки. Вот [здесь](https://ruby-doc.org/core-2.4.1/Enumerable.html) есть список всех методов модуля `Enumerable`, который включён в класс [Range](https://ruby-doc.org/core-2.4.1/Range.html) (синтаксис типа `x...y` порождает объект этого класса).

2017-04-26 03:09 UTC, be9 commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +  @N = a.length
А зачем здесь `@N`? Потому что просто `N = a.length` тебе не дали написать?

Используй `n = a.length`. `@N` будет инстанс-переменной у объекта main, чего совсем не хочется.

2017-04-26 03:09 UTC, be9 commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +  for i in 0...@N
Обычно для циклов пишут `(0...n).each do |i| ... end`. Разница в том, что `for` не открывает новый scope, а `.each` открывает.

2017-04-26 03:09 UTC, be9 commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +    end
Всё это можно заменить на одну строку: 

```ruby
    min = (i...n).min { |p, q| a[p] <=> a[q] }
```

2017-04-26 03:09 UTC, be9 commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +def selection_sort2(a)
В этой функции всё поправить аналогично.

2017-04-26 03:20 UTC, be9 commented
Ещё ремарка по поводу однострочников.

Ruby — не функциональный язык программирования, но все эти `.each`, `.min`, `.all?` и прочие `.map` и `.select` — это чистой воды функциональщина. Идея в том, что разделяется «большая» функция-алгоритм, реализующая цикл, условия выхода, сбор возвращаемого значения, и «маленькая» функция, что-то делающая для отдельного элемента в конкретном случае. В Ruby «большие» функции обычно реализуются как методы, а «маленькие» — как блоки. Блоки имеют доступ к окружающим переменным (это т.н. «замыкание», closure), поэтому всё удобно.

2017-04-30 17:53 UTC, v-log commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +  @N = a.length
@be9 Понял. Все это, по идее, должно быть в классе (типа SelectionSort)? Если бы был класс, то можно было бы использовать @N (как переменную экземпляра)?

2017-04-30 17:57 UTC, v-log commented
@be9 А как понять, что какой-то метод, например - .min, принимает в блоке именно 2 параметра в ||? (ну в min можно догадаться, а там где непонятно, как быть?)

2017-05-01 03:38 UTC, be9 commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +  @N = a.length
Нет, класс здесь избыточен. Ведь вся логика помещается в одну функцию из нескольких строк.

2017-05-01 03:44 UTC, be9 commented
@v-log понять можно путём внимательного чтения документации. Например, вот про [min](https://ruby-doc.org/core-2.4.1/Enumerable.html#method-i-min): 
![2017-05-01_10-40-43](https://cloud.githubusercontent.com/assets/920/25571526/d162faa0-2e5a-11e7-85e7-106db48a6065.png). Если ещё почитать про [Comparable](https://ruby-doc.org/core-2.4.1/Comparable.html), который там поминается, то должно стать понятно, как всё это работает.

2017-05-01 03:50 UTC, be9 reviewed
Уже лучше 😃

2017-05-01 03:50 UTC, be9 commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +      get_var = lambda {|item| block_given? ? yield(item) : item}
Вот эту лямбду я бы вынес из циклов, работало бы быстрее. Поскольку замыкание всегда привязывается к контексту, в твоей реализации будут всё время создаваться новые объекты. А `block_given?` можно вынести из тела лямбды. Т.е. `get_var = block_given? ? lambda { |item| yield(item) } : lambda { |item| item }`.

2017-05-01 03:50 UTC, be9 commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +      var1 <=> var2
Со свойственной для Ruby минималистичностью: `get_var[a[p]] <=> get_var[a[q]]`.

2017-05-01 04:38 UTC, v-log commented
@be9 Мда, глупый вопрос задал... Наверное, я что-то другое хотел сказать...
Я смотрел описание .min в Range, а там было так:
![image](https://cloud.githubusercontent.com/assets/19331788/25572142/5c717d54-2e62-11e7-9b5b-d15f484cf25b.png)
И не понимал что к чему

2017-05-01 14:41 UTC, v-log commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +      get_var = lambda {|item| block_given? ? yield(item) : item}
@be9 "I see what you did there" )

2017-05-01 14:45 UTC, v-log commented on RUBY/2_1_SortAlgs/selection_sort.rb
> +      var1 <=> var2
@be9  Так не честно, я этого еще не знал) Нашел книгу Д.Флэнагана и Матсумото "The Ruby Programming Language", а то сюрпризы в языке, хоть и приятные, всплывают постоянно)

2017-05-02 03:51 UTC, be9 approved these changes

2017-05-02 03:53 UTC, be9 commented
Ну что, получился неплохой код на Ruby! Ёмкий и выразительный. Это элемент культуры Ruby.

2017-05-02 11:42 UTC, v-log commented
@be9 По поводу коммитов хотел спросить - к ним комментарии как обычно пишут: описывают непосредственно изменения в коде, "как сделано" (как здесь последний коммит, например), или "что сделано" ([75a1233](https://github.com/v-log/Training/pull/41/commits/75a1233c80f8108c097fbdd9f27bdbf0a6c16e39)) ?

2017-05-02 11:54 UTC, be9 commented
@v-log Обычно «что сделано» и «зачем» (последнее обычно идёт в описание коммита). «Как сделано» — эту информацию несёт в себе сам коммит, конкретные изменения файлов. Можно всегда его посмотреть.

2017-05-02 12:08 UTC, be9 commented
Вот ещё что хочу показать: как делать тесты. https://gist.github.com/anonymous/c42efcedbc386eeeff6892aba9d854c1

Этот файл можно просто запустить: `ruby how_to_test.rb`.

Доки [здесь](http://docs.seattlerb.org/minitest/).

2017-05-06 08:34 UTC, merged