Алгоритм сортировки вставкой на Ruby
v-log/Training pull request #42
Opened 2017-05-06 14:36 UTC by v-log

2017-05-06 14:39 UTC, v-log commented
@be9 В test_insertion_sort в `expected` вставлял `[1,2,3,4,5]`, но `actual` выходил (1...5), поэтому так оставил. Почему так происходит?

2017-05-06 16:11 UTC, be9 requested changes
См. комменты, там есть разгадка к твоему вопросу

2017-05-06 16:11 UTC, be9 commented on RUBY/lib/2_1_SortAlgs/insertion_sort.rb
> +    (i).downto(1).each do |j|
Здесь делаются лишние операции. Как только станет `a[j] > a[j-1]`, цикл надо останавливать. Лучше использовать `while` и `break`.

2017-05-06 16:11 UTC, be9 commented on RUBY/lib/2_1_SortAlgs/insertion_sort.rb
> +  end
Сейчас функция возвращает `1...n`, потому что `Enumerable#each` возвращает `self`. Надо бы в конец добавить `a`, тогда и тесты заработают.

2017-05-06 16:11 UTC, be9 commented on RUBY/tests/insertion_sort_test.rb
> +    assert_equal (1...5), insertion_sort(@unsorted_arr)
Тут надо либо добавить правильное возвращаемое значение в `insertion_sort` (см. выше), либо писать

```ruby
insertion_sort(@unsorted_arr)
assert_equal [1,2,3,4,5], @unsorted_arr
```

2017-05-06 16:45 UTC, v-log commented on RUBY/lib/2_1_SortAlgs/insertion_sort.rb
> +    (i).downto(1).each do |j|
@be9 Осознал

2017-05-06 16:46 UTC, v-log commented on RUBY/lib/2_1_SortAlgs/insertion_sort.rb
> +    (i).downto(1).each do |j|
@be9 А можно без break а в while через `&&` условия поставить?

2017-05-06 16:47 UTC, v-log commented on RUBY/tests/insertion_sort_test.rb
> +    assert_equal (1...5), insertion_sort(@unsorted_arr)
@be9 Тут ничего, если Expected все в #setup объявляются?

2017-05-07 04:19 UTC, be9 reviewed
Уже хорошо, давай еще добавим полезный тест.

2017-05-07 04:19 UTC, be9 commented on RUBY/tests/insertion_sort_test.rb
> +  def test_not_sorted
Это бессмысленный тест.

2017-05-07 04:19 UTC, be9 commented on RUBY/tests/insertion_sort_test.rb
> +  end
Я бы еще добавил тест со случайно генерируемым массивом из, допустим, 100 элементов от 0 до 99. Сортировать его стандартным способом, insertion, и сравнить.

2017-05-07 18:18 UTC, v-log commented on RUBY/tests/insertion_sort_test.rb
> +  def test_not_sorted
@be9 Изменил на refute. Почему бессмысленый? Надо же проверить, что он не постоянно true выдает, нет?

2017-05-07 18:21 UTC, v-log commented on RUBY/tests/insertion_sort_test.rb
> +  end
@be9 В тесте с хешами при использовании rand появлялись одинаковые значения, а результат сравнения одинаковых значений, по документации, непредсказуем, поэтому assert_equal не всегда проходил; использован shuffle во избежание повторяющихся значений.

2017-05-08 09:14 UTC, v-log commented on RUBY/tests/insertion_sort_test.rb
> +  end
@be9 Хотя, сейчас подумал, что разницы-то быть не должно, если значения одинаковые. Может, копирование хеша неправильно сделано было?

2017-06-07 10:03 UTC, v-log commented
@be9 А здесь как дела?

2017-06-08 05:31 UTC, be9 commented on RUBY/lib/2_1_SortAlgs/insertion_sort.rb
> +    (i).downto(1).each do |j|
Можно

2017-06-08 05:32 UTC, be9 commented on RUBY/tests/insertion_sort_test.rb
> +    assert_equal (1...5), insertion_sort(@unsorted_arr)
норм

2017-06-08 05:33 UTC, be9 commented on RUBY/tests/insertion_sort_test.rb
> +  end
Если значения одинаковые, то ключи просто перезапишутся. Но и shuffle пойдёт.

2017-06-08 05:34 UTC, be9 commented on RUBY/tests/insertion_sort_test.rb
> +  def test_not_sorted
Да, если это тест для `sorted?`, то полезный :)

2017-06-08 05:38 UTC, be9 approved these changes
В целом хорошо (разве что each + push можно поменять на map).

2017-06-08 05:38 UTC, be9 commented on RUBY/tests/insertion_sort_test.rb
> +    (0...permutation.size).each { |i| pairs.push [i, permutation[i]] }
Предыдущие две строки заменяются на 

```ruby
pairs = (0...permutation.size).map { |i| [i, permutation[i]] }
```

2017-06-08 13:39 UTC, v-log commented on RUBY/tests/insertion_sort_test.rb
> +    (0...permutation.size).each { |i| pairs.push [i, permutation[i]] }
@be9  А, так тут map должен быть... Просто Вы в #43 писали 
 `pairs = (0...permutation.size).each { |i| [i, permutation[i]] }`
Я попробовал тогда, не заработало, поэтому через push сделал.

2017-06-08 14:07 UTC, be9 commented on RUBY/tests/insertion_sort_test.rb
> +    (0...permutation.size).each { |i| pairs.push [i, permutation[i]] }
Это я сплоховал. `.each` возвращает тот же объект, а `.map` делает отображение —трансформацию элементов структуры данных с помощью переданной функции (в Ruby для этого используется блок).

2017-06-08 14:09 UTC, v-log commented on RUBY/tests/insertion_sort_test.rb
> +    (0...permutation.size).each { |i| pairs.push [i, permutation[i]] }
@be9 Понял

2017-06-08 14:09 UTC, merged