Merge sort
v-log/Training pull request #51
Opened 2018-01-30 01:51 UTC by v-log

2018-01-30 01:52 UTC, v-log commented
@be9  Реализация merge_sort  на Ruby

2018-01-30 03:30 UTC, v-log commented
@be9 Вопрос: 
Здесь методы изменяют непосредственно входные данные и работают и без возврата 'а' в конце. Оставил для лучшей читаемости, ничего? Или обычно ничего не ставят?

2018-02-07 04:47 UTC, be9 commented on RUBY/lib/2_2_merge_sort/merge_sort.rb
> +    merge_sort_hlpr!(a, 0, a.size - 1, aux, &Proc.new)
А это что за жесть такая с `&Proc.new`?

2018-02-07 04:53 UTC, be9 requested changes
С блоками напутано немного. Можно проще (см. комментарии).

2018-02-07 04:53 UTC, be9 commented on RUBY/lib/2_2_merge_sort/merge_sort.rb
> +def merge_sort_hlpr!(a, lo, hi, aux)
Лучше здесь явно написать передачу блока:

```ruby
def merge_sort_hlpr!(a, lo, hi, aux, &block)
  # ...
end
```
и считать, что он передается всегда. И его же передавать в `merge!`. А вместо этого:

```ruby
get_var = block_given? ? lambda { |item| yield (item) } : lambda { |item| item }
...
get_var[aux[i]]
```
просто писать `block.call(aux[i])`.

А в `merge_sort!` тоже сделать `&block`. Если он нулевой, передавать вместо него `Proc.new { |x| x }`.

2018-03-24 18:00 UTC, v26 commented
@be9 Ничего, что все коммиты заливаю, или лучше использовать cherry-pick?

2018-03-27 08:30 UTC, be9 commented
@v-log Можно потом смержить с "Squash and merge".

2018-04-09 12:18 UTC, be9 approved these changes

2018-04-09 12:35 UTC, merged