Решение задачи 1.2.16 (пока без 1.2.17)
v-log/Training pull request #9
Opened 2016-09-07 15:00 UTC by v-log

У рациональных чисел знаменатель - натуральное число, но я решил не делать исключение на случай ввода отриц. знаменателя, а просто изменить/поменять местами знаки.
В поиск НОД внесено небольшое изменение - сравниваются модули двух чисел. Так как со знаками мы разбираемся в конструкторе, это изменение не повлияет на конечный результат, просто это удобнее.

2016-09-11 19:06 UTC, v-log commented
@be9 Добавил assert'ы, но выражения для них просто противоположны тем, что в исключениях. 
Я понимаю, что assert нужно использовать для выявления источника той или иной ошибки. Но чем это отличается от тех же исключений, которые то же самое могут делать?

2016-09-15 04:00 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +        if ( gcdThis > 1 ) {
Вообще-то все дроби приводятся в конструкторе, поэтому дополнительно делать это здесь не нужно и даже вредно. Возникает дублирование, а опаснее всего не само дублирование, а то, что каждый раз процедура может быть чуть разной.

Здесь яркий пример: в конструкторе ты уносишь знак в числитель, т.е. можно предполагать, что знаменатель всегда положителен. А здесь эта проверка не делается. И поэтому дроби (-1/2) и (1/-2) были бы не равны, если бы приведения в конструкторе не было.

2016-09-15 04:10 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +        assert ((a & b & ~c) | (~a & ~b & c)) >= 0 : "long overflow sPlus(" + a + ", " + b + ")";
Тут либо `assert`, или `throw new ArithmeticException`. Собственно, `assert` внутри себя делает `throw new AssertionError`.

Поскольку ситуацию переполнения мы рассматриваем как возможную и специально её обрабатываем, `assert` не нужен. Он нужен для проверки пред- или постусловий, невыполнение которых рассматривается как заведомо ошибочная ситуация. Можно здесь почитать http://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html

2016-09-15 04:11 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +        assert (a == c2) : "long overflow sTimes(" + a + ", " + b + ")";
Аналогично с assert.

2016-09-15 04:12 UTC, be9 requested changes

2016-09-15 04:12 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +        long gcd = gcd( numer, denom );
Лучше не называть переменные так же, как методы. В Java и C++ компилятор ещё разберётся, а вот в других языках (типа JavaScript) будет проблема.

Кроме того, аргументы конструктора маскируют поля (numer и denom). Обычно их называют либо немного по-другому (например,  num и den), либо добавляют _: _number, _denom. Эти простые правила позволяют избежать путаницы.

2016-09-15 04:12 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +            this.numer = numer * (-1);
Это унарный минус.

```
this.numer = -numer;
this.denom = -denom;
```

2016-09-15 04:12 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +            if ( gcdSum > 1) {
Логика с сокращением числителя и знаменателя на НОД дублируется два раза. Зачем это делать здесь, когда при вызове конструктора (`sum = new Rational()`) это произойдёт опять?

2016-09-15 04:12 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +        long subNumer;
Обычно вычитание делается на основе сложения. Собственно, сложение должно и так работать с отрицательными числителями, так что вычитание — сложение с дробью с обращённым знаком.

2016-09-15 04:12 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +        long divNumer;
Аналогично вычитанию: деление — это умножение на обращённую дробь.

2016-09-19 06:23 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +            Rational rat1 = new Rational(1, Long.parseLong(a));
А зачем эти Long.parseLong?

Можно же написать `9223372036854775808L`. Суффикс `L` означает, что константу надо воспринимать как Long.

2016-09-19 06:23 UTC, be9 requested changes
Почти :)

2016-09-19 15:04 UTC, v-log commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +            Rational rat1 = new Rational(1, Long.parseLong(a));
@be9 А это такой ход: если просто вписать число как аргумент в конструктор, выйдет ошибка "integer number too large", а если через строку задать, то исключение вылезет как нужно. Я тут хотел проверить, что он исключение выкинет при переполнении. 
И вот сейчас подумал... Он ведь так и так выкинет, это проверять не нужно?

2016-09-19 18:00 UTC, v-log commented
Обнаружилась ошибка в конструкторе SmartDate(String date)

2016-09-20 05:34 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +            Rational rat1 = new Rational(1, Long.parseLong(a));
Здесь integer number too large означает, что константа 9223372036854775808 попросту не влезает в обычный `int`. Тип `long` имеет большую разрядность, и с ним проблем нет. А если суффикс `L` прибавить к числу, то константа будет сразу восприниматься как long.

2016-09-20 17:04 UTC, v-log commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +            Rational rat1 = new Rational(1, Long.parseLong(a));
@be9 Это я понимаю, внизу в другом тесте я так и сделал. Но  integer закончился еще на 2147483647, Long заканчивается на 9223372036854775807, и дальше я и добавлял L, чтобы воспринимал его не как int, а как long. А число 9223372036854775808L уже выходит и за long, поэтому я и закидывал его в String, чтобы можно было запустить

2016-09-21 03:23 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +            Rational rat1 = new Rational(1, Long.parseLong(a));
Ясно

2016-09-21 03:25 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +                long aNumer = Long.parseLong(aArray[0]);
Здесь нет гарантии, что `aArray` будет длины 2 (как и `bArray`). Кстати, код создания дроби из строки повторяется, можно вынести его в отдельный метод.

2016-09-21 03:29 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +                        " в пределах интервала -2^62...2^64-1");
Если уж быть совсем точным, то диапазон знакового числа разрядности N в двоичном дополнительном коде простирается от -2^{N-1} до 2^{N-1}-1. :neckbeard:

2016-09-21 03:33 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +            sum = new Rational(sumNumer, aD);
Здесь я бы вообще отказался от переменной sum.

Код 

```java

Rational sum;

if (условие) {
    // .....полэкрана кода.....
    sum = new Rational(...);
} else {
    // .....полэкрана кода.....
    sum = new Rational(...);
}

return sum;
```

Можно заменить на

```java
if (условие) {
    // .....полэкрана кода.....
    return new Rational(...);
} else {
    // .....полэкрана кода.....
    return new Rational(...);
}
```

Это проще читается.

2016-09-21 03:36 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +            fail("Should throw NumberFormatException");
Всё же не очень понятно, зачем здесь эти тесты. NumberFormatException здесь будет выкидываться из Long.parseLong, т.е. ты тестируешь не свой код, до него даже исполнение не доходит.

2016-09-21 03:38 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +        Rational rat5 = new Rational(8, 6);
Можно не заводить дополнительные переменные, а сразу писать

```java
assertEquals(new Rational(8, 6), new Rational(4, 3));
```
Когда всё влазит в одну строку, это оправдано, потому что читается легче.

2016-09-21 03:39 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +        assertEquals(123, a1);
Аналогично `assertEquals(123, (new Rational(123, 1)).numerator()));`

2016-09-21 03:48 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +    }
Здесь не хватает теста на переполнение при умножении. 

Кстати, степени двойки удобнее записывать либо в 16-ричной системе, либо как выражение.

Например, страшное число `9223372036854775807L` можно записать как:

- `(1L << 63) - 1`
- `0x7fffffffffffffffL`
- `Long.MAX_VALUE`

В этом случае я предпочёл бы, конечно, последний вариант. Но и первые два лучше, чем число в десятичной системе.

2016-09-21 03:49 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +    }
Аналогично не хватает проверки переполнения.

2016-09-21 03:49 UTC, be9 requested changes

2016-09-22 10:54 UTC, v-log commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +        assertEquals(123, a1);
@be9 Просто прочел тоже рекомендацию по JUnit - советовали разделять на три этапа:
- создание объекта;
- применение к нему метода;
- сам assert.

Переделаю. Вопрос: переделывать так все тесты?
Просто, например, `assertEquals(new Rational(9, 8), new Rational(9, 5).divides(new Rational(8, 5)));` - нормально? А то я не уверен.

2016-09-22 10:56 UTC, v-log commented on src/Ex_1_2_16_1_2_17/Rational.java
> +                        " в пределах интервала -2^62...2^64-1");
@be9 62 - это была опечатка, но получается что нигде не попал в 63... :)

2016-09-22 10:58 UTC, v-log commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +            fail("Should throw NumberFormatException");
@be9 Вот про это я и спрашивал. Когда писал изначально код, не задумался об этом, потом только осенило (убрал их).

2016-09-23 08:19 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +                        " в пределах интервала -2^62...2^64-1");
@v-log Да. Но это навело меня на мысль, что в рамках нашего обучения нужно устроить небольшой спецкурс по работе с битами. 😉

2016-09-23 08:32 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +        assertEquals(123, a1);
Это уже многовато. Я бы разбил на два:

```java
Rational result = (new Rational(9, 5)).divides(new Rational(8, 5));
assertEquals(new Rational(9, 8), result);
```

В общем, лучше писать сжато, КРОМЕ тех случаев, когда это приводит к загромождению. Но разница субъективна. 

Попробуй провести небольшой эксперимент на калибровку восприятия: 

1. Реализуй какой-то выбранный вариант.
2. Запомни номер строки и перейди к началу файла (в IDEA вроде можно было также ставить метки внутри).
3. Отвлекись на 30 сек на что-нибудь другое.
4. Вернись к файлу, перейди к заданному номеру строки или к метке (для этого есть хоткеи).
5. ...А теперь оцени, насколько быстро ты можешь врубиться, что тут написано.

Собственно, цель любого форматирования и структурирования кода — минимизировать время, требуемое на понимание смысла. Перебрав таким образом несколько вариантов написания одного и того же, ты можешь экспериментально подобрать то, что подойдёт тебе.

2016-09-23 23:03 UTC, v-log commented on src/Ex_1_2_16_1_2_17/Rational.java
> +                        " в пределах интервала -2^62...2^64-1");
@be9 Доверюсь Вашему чутью)

2016-09-24 04:53 UTC, be9 commented on src/Ex_1_2_16_1_2_17/Rational.java
> +                System.out.println("Введите числитель и знаменатель через / для каждого числа" +
Строка «Введите числитель и знаменатель…» повторяется 3 раза, это уже многовато. Два раза ещё можно было бы стерпеть.

2016-09-24 04:55 UTC, be9 commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +    // Тест на перехват нуля в знаменателе
Комментарии обычно равняются вместе с кодом, на том же уровне отступа (здесь и далее).

2016-09-24 04:55 UTC, be9 requested changes

2016-09-24 06:51 UTC, v-log commented on tests/Ex_1_2_16_1_2_17/RationalTest.java
> +    // Тест на перехват нуля в знаменателе
Показалось, так воспринимается лучше, чем вровень

2016-10-10 14:36 UTC, merged